# Generated by Django 3.1 on 2020-11-26 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='release date'),
        ),
    ]
